DROP TABLE IF EXISTS TB_DEFEITO_PECA;
DROP TABLE IF EXISTS TB_PECA_VEICULO;
DROP TABLE IF EXISTS TB_DEFEITO;
DROP TABLE IF EXISTS TB_PECA;
DROP TABLE IF EXISTS TB_VEICULO;

CREATE TABLE IF NOT EXISTS TB_DEFEITO(
	idDefeito INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TB_PECA(
	idPeca INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TB_VEICULO(
	idVeiculo INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TB_DEFEITO_PECA(
	idDefeitoPeca INT AUTO_INCREMENT PRIMARY KEY,
	fkIdDefeito INT NOT NULL,
	fkIdPeca INT NOT NULL,
	FOREIGN KEY (fkIdDefeito) REFERENCES TB_DEFEITO(idDefeito),
	FOREIGN KEY (fkIdPeca) REFERENCES TB_PECA(idPeca)
);

CREATE TABLE IF NOT EXISTS TB_PECA_VEICULO(
	idPecaVeiculo INT AUTO_INCREMENT PRIMARY KEY,
	fkIdPeca INT NOT NULL,
	fkIdVeiculo INT NOT NULL,
	FOREIGN KEY (fkIdPeca) REFERENCES TB_PECA(idPeca),
	FOREIGN KEY (fkIdVeiculo) REFERENCES TB_VEICULO(idVeiculo)
);

CREATE TABLE IF NOT EXISTS TB_REGISTRO(
	idRegistro INT AUTO_INCREMENT PRIMARY KEY,
	nomeCliente VARCHAR(100) NOT NULL,
	fkIdDefeitoPeca INT NOT NULL,
	fkIdPecaVeiculo INT NOT NULL,
	data TIMESTAMP NOT NULL,
	FOREIGN KEY (fkIdDefeitoPeca) REFERENCES TB_DEFEITO_PECA(idDefeitoPeca),
	FOREIGN KEY (fkIdPecaVeiculo) REFERENCES TB_PECA_VEICULO(idPecaVeiculo)
);

INSERT INTO TB_DEFEITO (nome) VALUES
('Queimado'),
('Ferrugem'),
('Quebrado'),
('Furado'),
('Amassado');

INSERT INTO TB_PECA (nome) VALUES
('Motor'),
('Helice',
('Pneu'),
('Volante'),
('Roda'),
('Eixo');

INSERT INTO TB_VEICULO (nome) VALUES
('Carro'),
('Moto'),
('Barco');